name: curl
description: Generate output equivalent to the "copy as curl" option with HTTP client debugger.
version: 1.0.0
homepage: https://github.com/kiruto/curl
author: Yuriel <yuriel3183@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0+1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
